FROM python:3.12-slim

WORKDIR /app

# Install poetry
RUN pip install poetry

# Copy only pyproject.toml and poetry.lock (if it exists)
COPY pyproject.toml poetry.lock* ./

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Copy the careai folder
COPY careai ./careai

# Copy config folder with all yamls
COPY config ./config

# Set the working directory to the careai folder
WORKDIR /app/


# Command to run the application
CMD ["poetry", "run", "uvicorn", "careai.api_main:app", "--host", "0.0.0.0", "--port", "8000"]